version: '3.6'

services:
  orca-server:
    container_name: orca-server
    image: quay.io/plotly/orca:latest
    restart: always
    networks:
      - play

  playground:
    container_name: playground
    depends_on:
      - orca-server
##  image: bigomics/omicsplayground:latest
    image: bigomics/omicsplayground:test
    volumes:
      - /var/log/apache2:/omicsplayground/xlib/apache2.log      
##      - ~/pgx_data:/omicsplayground/data
    ports:
      - 4000:3838
    networks:
      - play
    restart: always
    environment:
      ORCA_SERVER: orca-server:9091

##volumes:
##   omxp_data: {}

networks:
  play:
    driver: bridge
